# Generated by Django 5.0.7 on 2024-07-26 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='exerpt',
            new_name='excerpt',
        ),
    ]
